server:
  port: 9005

spring:
  application:
    name: order
  datasource:
    type:  com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    fetch-registry: true # 从注册中心检索服务
    register-with-eureka: true #注册中心注册自己
    service-url:
      # defaultZone: http://localhost:7001/eureka/ #单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.love.family.entities #所有entities别名类所在包
