server:
  port: 9001

spring:
  application:
    name: order

eureka:
  client:
    fetch-registry: true # 从注册中心检索服务
    register-with-eureka: true #注册中心注册自己
    service-url:
      # defaultZone: http://localhost:7001/eureka/ #单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版
